#!/usr/bin/env python3
"""CI-level monotonic baseline policy (batch-4 item 11).

`baseline.py`'s `check_metric()` already enforces an EXACT match between a
freshly computed metric and `baselines.json` within a single commit — but
that alone can't stop someone from silently RAISING a baseline (accepting
a real regression) in the same commit that also "legitimately" updates it,
since exact-match-in-this-commit says nothing about the PREVIOUS committed
value. This script is the missing piece: compare HEAD's committed
`scripts/av-ru-1967/baselines.json` (already regenerated by `build_all.sh`
before this script runs) against the same file at a `--base-ref` (a PR's
target branch, or the previous commit on a direct push) and fail if any
metric's *baseline* increased (got worse) without an explicit approval
marker in the HEAD commit message. Also verifies `report.md`'s
`evaluated_commit` field is a real ancestor of HEAD (see
`check_report_freshness()` for why a literal self-hash is impossible).

Policy (av-ru-1967-review-batch-4-2026-09-17.md, "11. Добавить monotonic
baseline policy в CI"):
- metric worse than its OWN baseline in this commit: already a hard
  failure via `baseline.py`'s exact-match check (build_all.sh already
  failed before this script would even run) — not re-checked here.
- baseline value increased vs. `--base-ref`: failure, unless the HEAD
  commit message contains a `baseline-regression-approved: <reason>`
  trailer line.
- baseline value decreased vs. `--base-ref` (a real improvement): always
  fine.
- a metric missing from either side: failure (a metric must never
  silently disappear from tracking, nor appear without a matching entry
  on the base side being at least considered — new metrics ARE allowed,
  they just can't already exist on both sides with a worse value here).

Run from repo root, after `build_all.sh` has already produced the current
`scripts/av-ru-1967/baselines.json` (this script only reads it — never
re-runs the pipeline itself).
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path

APPROVAL_RE = re.compile(r"^baseline-regression-approved:\s*\S", re.MULTILINE)
EVALUATED_COMMIT_RE = re.compile(r"^`?evaluated_commit:\s*([0-9a-f]{7,40})`?", re.MULTILINE)


def _git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def _git_ok(*args: str) -> bool:
    return subprocess.run(["git", *args], capture_output=True, text=True).returncode == 0


def check_report_freshness(report_path: str) -> bool:
    """A `report.md` can never literally contain its own resulting commit
    hash (the hash is computed FROM the file's content) — so instead of
    the impossible literal self-reference, verify the weaker, still
    meaningful invariant: the commit `report.md` claims to describe
    (`evaluated_commit: <sha>`) must be a real ancestor of (or equal to)
    HEAD, not a stale/foreign/future reference."""
    text = Path(report_path).read_text(encoding="utf-8")
    match = EVALUATED_COMMIT_RE.search(text)
    if not match:
        print(f"[ci-policy] FAIL: {report_path} has no 'evaluated_commit: <sha>' field")
        return False
    sha = match.group(1)
    if not _git_ok("cat-file", "-e", f"{sha}^{{commit}}"):
        print(f"[ci-policy] FAIL: {report_path}'s evaluated_commit {sha} does not exist in this repo")
        return False
    if not _git_ok("merge-base", "--is-ancestor", sha, "HEAD"):
        print(f"[ci-policy] FAIL: {report_path}'s evaluated_commit {sha} is not an ancestor of HEAD (stale or wrong reference)")
        return False
    print(f"[ci-policy] ok: {report_path}'s evaluated_commit {sha} is a real ancestor of HEAD")
    return True


def load_baselines_at_ref(ref: str, path: str) -> dict[str, int] | None:
    try:
        content = _git("show", f"{ref}:{path}")
    except subprocess.CalledProcessError:
        return None
    return json.loads(content)


def head_commit_message() -> str:
    return _git("log", "-1", "--format=%B")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baselines", default="scripts/av-ru-1967/baselines.json")
    parser.add_argument("--report", default="scripts/av-ru-1967/report.md")
    parser.add_argument(
        "--base-ref",
        required=True,
        help="git ref to compare against (e.g. origin/main for a PR, or HEAD~1 for a direct push).",
    )
    args = parser.parse_args()

    ok = check_report_freshness(args.report)

    current = json.loads(Path(args.baselines).read_text(encoding="utf-8"))
    base = load_baselines_at_ref(args.base_ref, args.baselines)
    if base is None:
        print(f"[ci-policy] {args.baselines} does not exist at {args.base_ref} — treating as a brand-new file, nothing to compare, ok")
        return 0 if ok else 1

    approved = bool(APPROVAL_RE.search(head_commit_message()))

    all_keys = sorted(set(current) | set(base))
    for key in all_keys:
        if key not in current:
            print(f"[ci-policy] FAIL: {key} existed at {args.base_ref} but is missing from HEAD (a metric must never silently disappear)")
            ok = False
            continue
        if key not in base:
            print(f"[ci-policy] ok: {key} = {current[key]} is new (no baseline at {args.base_ref} to compare against)")
            continue
        cur_val, base_val = current[key], base[key]
        if cur_val > base_val:
            if approved:
                print(f"[ci-policy] APPROVED REGRESSION: {key} {base_val} -> {cur_val} (baseline-regression-approved trailer found in HEAD commit message)")
            else:
                print(
                    f"[ci-policy] FAIL: {key} baseline increased {base_val} -> {cur_val} vs {args.base_ref} "
                    "(a real regression was accepted without an explicit approval marker — add a "
                    "'baseline-regression-approved: <reason>' trailer to the commit message if this is intentional)"
                )
                ok = False
        elif cur_val < base_val:
            print(f"[ci-policy] ok: {key} improved {base_val} -> {cur_val} vs {args.base_ref}")
        else:
            print(f"[ci-policy] ok: {key} unchanged ({cur_val}) vs {args.base_ref}")

    if not ok:
        print("[ci-policy] HARD GATE FAILED: one or more baselines regressed without approval")
        return 1
    print("[ci-policy] all baselines are monotonic (or explicitly approved) vs", args.base_ref)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
