#!/usr/bin/env python3
"""CI-level monotonic baseline policy (batch-4 item 11, reworked per
av-ru-1967-review-batch-5-2026-09-18.md's P0 "Переделать monotonic
baseline CI policy").

`baseline.py`'s `check_metric()` already enforces an EXACT match between a
freshly computed metric and `baselines.json` within a single commit — but
that alone can't stop someone from silently RAISING a baseline (accepting
a real regression) in the same commit that also "legitimately" updates
it, since exact-match-in-this-commit says nothing about the PREVIOUS
committed value. This script is the missing piece, comparing HEAD's
committed `baselines.json` (already regenerated by `build_all.sh` before
this script runs) against an earlier point in history.

Batch-5 found three gaps in the first version of this script:

1. A PR merging into a base branch that has never had `baselines.json`
   (e.g. the very first merge of this feature branch into `main`) got
   ZERO protection — "brand-new file, nothing to compare, ok" silently
   let any starting values through, even ones that regressed relative to
   this branch's OWN prior history. Fixed: `find_comparison_baselines()`
   now falls back to walking HEAD's own first-parent history for the
   nearest ancestor commit that DOES have the file, whenever the given
   `--base-ref` doesn't (`main` not having it yet doesn't mean nothing
   should be checked — the feature branch's own history still should be).
2. Comparing only against `HEAD~1` (the direct-push default) never
   catches a metric that quietly disappeared several commits earlier —
   each individual step's diff looked fine at the time. Fixed: a metric
   present in the comparison baseline but missing from HEAD is INVALID
   unless it has a matching entry in `baseline_migrations.json` (a
   permanent, committed audit trail of legitimate removals) — so it's
   safe to compare against an arbitrarily old ref (as batch-5's own
   reproduction, `--base-ref 05fb50e`, does) without false-failing on
   migrations that were already properly documented.
3. A single unscoped `baseline-regression-approved: <reason>` trailer
   approved EVERY regressed metric in the commit at once. Fixed: the
   trailer format is now per-metric and value-specific
   (`baseline-regression-approved: <metric> <old>-><new> reason: <text>`)
   — an approval only covers the metric/values it explicitly names.
4. `report.md`'s `evaluated_commit` being ANY ancestor of HEAD never
   expires — a report written months ago describing a long-superseded
   state stays "valid" forever under that check alone (batch-5 caught
   `report.md` itself doing exactly this: an old "Current metrics"
   section still showing 9858 entries / 408 regressions / 495 missing
   links long after those numbers changed). Fixed: `report.md` must carry
   a machine-readable manifest (a fenced ```json block with
   `evaluated_commit` + a sha256 for every committed generated artifact +
   `baselines.json`) and `check_report_freshness()` now (a) requires
   `evaluated_commit` be HEAD or HEAD's immediate parent — not just any
   ancestor — and (b) recomputes every artifact's sha256 ON DISK right
   now and requires an EXACT match against the manifest, so a report
   whose manifest doesn't match the files it claims to describe fails,
   regardless of how plausible its commit reference looks.

Run from repo root, after `build_all.sh` has already produced the current
`scripts/av-ru-1967/baselines.json` (this script only reads it — never
re-runs the pipeline itself).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
from pathlib import Path
from typing import Any

MANIFEST_RE = re.compile(r"```json\s*\n(\{.*?\})\s*\n```", re.DOTALL)
APPROVAL_RE = re.compile(
    r"^baseline-regression-approved:\s*(?P<metric>\S+)\s+(?P<old>-?\d+)->(?P<new>-?\d+)\s+reason:\s*(?P<reason>.+)$",
    re.MULTILINE,
)


def _git(*args: str) -> str:
    return subprocess.run(["git", *args], capture_output=True, text=True, check=True).stdout


def _git_ok(*args: str) -> bool:
    return subprocess.run(["git", *args], capture_output=True, text=True).returncode == 0


def load_baselines_at_ref(ref: str, path: str) -> dict[str, int] | None:
    try:
        content = _git("show", f"{ref}:{path}")
    except subprocess.CalledProcessError:
        return None
    return json.loads(content)


def find_comparison_baselines(base_ref: str, path: str) -> tuple[str, dict[str, int]] | None:
    """The ref to actually compare against: `base_ref` itself if it has
    the file, otherwise the nearest ancestor of HEAD (walking first-parent
    history) that does — so a PR into a base branch that has never had
    this file (e.g. the first merge into `main`) still gets compared
    against the feature branch's own prior committed state, not silently
    skipped. Returns None only if NO commit reachable from HEAD has ever
    had the file (a genuinely brand-new file, nothing to compare)."""
    direct = load_baselines_at_ref(base_ref, path)
    if direct is not None:
        return base_ref, direct
    for sha in _git("rev-list", "--first-parent", "HEAD").splitlines():
        found = load_baselines_at_ref(sha, path)
        if found is not None:
            return sha, found
    return None


def head_commit_message() -> str:
    return _git("log", "-1", "--format=%B")


def load_migrations(path: str) -> dict[str, dict[str, Any]]:
    p = Path(path)
    if not p.exists():
        return {}
    rows = json.loads(p.read_text(encoding="utf-8"))
    return {row["metric"]: row for row in rows}


def parse_approvals(commit_message: str) -> dict[str, tuple[int, int, str]]:
    """metric -> (old, new, reason), one entry per per-metric trailer
    line. Only THIS exact old->new transition is approved — a different
    value change for the same metric name still fails."""
    approvals: dict[str, tuple[int, int, str]] = {}
    for m in APPROVAL_RE.finditer(commit_message):
        approvals[m.group("metric")] = (int(m.group("old")), int(m.group("new")), m.group("reason").strip())
    return approvals


def compare_baselines(
    current: dict[str, int],
    base: dict[str, int],
    approvals: dict[str, tuple[int, int, str]],
    migrations: dict[str, dict[str, Any]],
) -> list[str]:
    """Pure comparison logic (no git I/O) — returns a list of failure
    messages; empty means the policy passes. Kept separate from git
    plumbing so it's directly unit-testable (see test_check_ci_policy.py)."""
    failures: list[str] = []
    for key in sorted(set(current) | set(base)):
        if key not in current:
            migration = migrations.get(key)
            if migration:
                print(f"[ci-policy] ok: {key} removed per documented migration ({migration['removed_at_commit'][:12]}): {migration['reason'][:80]}...")
            else:
                failures.append(
                    f"{key} existed in the comparison baseline but is missing from HEAD, with no "
                    f"entry in baseline_migrations.json documenting why (a metric must never silently disappear)"
                )
            continue
        if key not in base:
            print(f"[ci-policy] ok: {key} = {current[key]} is new (no prior baseline to compare against)")
            continue
        cur_val, base_val = current[key], base[key]
        if cur_val > base_val:
            approval = approvals.get(key)
            if approval and approval[0] == base_val and approval[1] == cur_val:
                print(f"[ci-policy] APPROVED REGRESSION: {key} {base_val} -> {cur_val} ({approval[2]})")
            else:
                failures.append(
                    f"{key} baseline increased {base_val} -> {cur_val} without a matching "
                    f"'baseline-regression-approved: {key} {base_val}->{cur_val} reason: ...' trailer in the HEAD commit message"
                )
        elif cur_val < base_val:
            print(f"[ci-policy] ok: {key} improved {base_val} -> {cur_val}")
        else:
            print(f"[ci-policy] ok: {key} unchanged ({cur_val})")
    return failures


def _sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def check_report_freshness(report_path: str) -> bool:
    """A `report.md` can never literally contain its own resulting commit
    hash (the hash is computed FROM the file's content) — so instead of
    the impossible literal self-reference, require the next best thing:
    a machine-readable manifest (a fenced ```json block) naming the
    commit it describes (HEAD or HEAD's immediate parent — not just any
    ancestor, which never expires) AND a sha256 for every committed
    generated artifact plus `baselines.json`, each independently
    recomputed from the files on disk right now and required to match
    EXACTLY — so the report can't silently drift from the state it
    claims to describe, however plausible its commit reference looks."""
    text = Path(report_path).read_text(encoding="utf-8")
    match = MANIFEST_RE.search(text)
    if not match:
        print(f"[ci-policy] FAIL: {report_path} has no machine-readable ```json manifest block")
        return False
    try:
        manifest = json.loads(match.group(1))
    except json.JSONDecodeError as e:
        print(f"[ci-policy] FAIL: {report_path}'s manifest block is not valid JSON: {e}")
        return False

    sha = manifest.get("evaluated_commit")
    if not sha or not _git_ok("cat-file", "-e", f"{sha}^{{commit}}"):
        print(f"[ci-policy] FAIL: {report_path}'s evaluated_commit {sha!r} does not exist in this repo")
        return False
    resolved = _git("rev-parse", sha).strip()
    head = _git("rev-parse", "HEAD").strip()
    head_parent = _git("rev-parse", "HEAD~1").strip() if _git_ok("rev-parse", "HEAD~1") else None
    if resolved not in (head, head_parent):
        print(
            f"[ci-policy] FAIL: {report_path}'s evaluated_commit {sha} ({resolved[:12]}) is neither HEAD "
            f"({head[:12]}) nor HEAD~1 ({(head_parent or '?')[:12]}) — stale report"
        )
        return False

    ok = True
    for rel_path, expected_hash in manifest.get("artifact_hashes", {}).items():
        if not Path(rel_path).exists():
            print(f"[ci-policy] FAIL: manifest names {rel_path} but it does not exist on disk")
            ok = False
            continue
        actual_hash = _sha256_file(rel_path)
        if actual_hash != expected_hash:
            print(f"[ci-policy] FAIL: {rel_path} sha256 on disk ({actual_hash[:12]}) does not match the manifest ({expected_hash[:12]})")
            ok = False
        else:
            print(f"[ci-policy] ok: {rel_path} matches the manifest's recorded hash")

    baselines_hash = manifest.get("baselines_hash")
    if baselines_hash:
        actual = _sha256_file("scripts/av-ru-1967/baselines.json")
        if actual != baselines_hash:
            print(f"[ci-policy] FAIL: scripts/av-ru-1967/baselines.json sha256 on disk ({actual[:12]}) does not match the manifest ({baselines_hash[:12]})")
            ok = False
        else:
            print("[ci-policy] ok: scripts/av-ru-1967/baselines.json matches the manifest's recorded hash")

    if ok:
        print(f"[ci-policy] ok: {report_path}'s manifest matches the current on-disk state exactly (evaluated_commit {sha[:12]})")
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--baselines", default="scripts/av-ru-1967/baselines.json")
    parser.add_argument("--migrations", default="scripts/av-ru-1967/baseline_migrations.json")
    parser.add_argument("--report", default="scripts/av-ru-1967/report.md")
    parser.add_argument(
        "--base-ref",
        required=True,
        help="git ref to compare against (e.g. the PR base branch tip, or HEAD~1 for a direct push).",
    )
    args = parser.parse_args()

    ok = check_report_freshness(args.report)

    current = json.loads(Path(args.baselines).read_text(encoding="utf-8"))
    found = find_comparison_baselines(args.base_ref, args.baselines)
    if found is None:
        print(f"[ci-policy] {args.baselines} has never existed on any commit reachable from HEAD — nothing to compare, ok")
        return 0 if ok else 1
    used_ref, base = found
    if used_ref != args.base_ref:
        print(f"[ci-policy] {args.baselines} does not exist at {args.base_ref} — falling back to nearest ancestor {used_ref}")

    migrations = load_migrations(args.migrations)
    approvals = parse_approvals(head_commit_message())
    failures = compare_baselines(current, base, approvals, migrations)
    for f in failures:
        print(f"[ci-policy] FAIL: {f}")
    ok = ok and not failures

    if not ok:
        print("[ci-policy] HARD GATE FAILED")
        return 1
    print(f"[ci-policy] all baselines are monotonic (or explicitly approved) vs {used_ref}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

